global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: "sensor-demo"

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["api:8000"]

  - job_name: "worker"
    static_configs:
      - targets: ["worker:8001"]